<?php
/**
 * Mage Solution
 * 2018
 */
?>

<?php
/* $block = \MGS\Marketplace\Block\Profile\Index */
$store = $block->getStoreProfile();
?>
<form id="store-profile" method="post" action="<?= $block->getPostUrl() ?>">
	<div class="row" id="r_twitter">
		<div class="row-title">Twitter ID <input type="checkbox" name="twitter_visibility"<?php echo $store->getTwitterVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="twitter_id" id="twitter_id" value="<?php echo $store->getTwitter(); ?>">
		</div>
	</div>
	<div class="row" id="r_facebook">
		<div class="row-title">Facebook ID <input type="checkbox" name="facebook_visibility"<?php echo $store->getFacebookVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="facebook_id" id="facebook_id" value="<?php echo $store->getFacebook(); ?>">
		</div>
	</div>
	<div class="row" id="r_youtube">
		<div class="row-title">Youtube ID <input type="checkbox" name="youtube_visibility"<?php echo $store->getYoutubeVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="youtube_id" id="youtube_id" value="<?php echo $store->getYoutube(); ?>">
		</div>
	</div>
	<div class="row" id="r_pinterest">
		<div class="row-title">Pinterest ID <input type="checkbox" name="pinterest_visibility"<?php echo $store->getPinterestVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="pinterest_id" id="pinterest_id" value="<?php echo $store->getPinterest(); ?>">
		</div>
	</div>
	<div class="row" id="r_instagram">
		<div class="row-title">Instagram ID <input type="checkbox" name="instagram_visibility"<?php echo $store->getInstagramVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="instagram_id" id="instagram_id" value="<?php echo $store->getInstagram(); ?>">
		</div>
	</div>
	<div class="row" id="r_googleplus">
		<div class="row-title">Google Plus ID <input type="checkbox" name="googleplus_visibility"<?php echo $store->getGoogleplusVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="googleplus_id" id="googleplus_id" value="<?php echo $store->getGoogleplus(); ?>">
		</div>
	</div>
	<div class="row" id="r_vimeo">
		<div class="row-title">Vimeo ID <input type="checkbox" name="vimeo_visibility"<?php echo $store->getVimeoVisibility()?' checked':'';?>></div>
		<div class="controls">
			<input type="text" class="input-text" name="vimeo_id" id="vimeo_id" value="<?php echo $store->getVimeo(); ?>">
		</div>
	</div>
	<div class="row" id="r_contact_number">
		<div class="row-title">Contact Number</div>
		<div class="controls">
			<input type="text" class="input-text" name="contact_number" id="contact_number" value="<?php echo $store->getTelephone(); ?>">
		</div>
	</div>
	<div class="row" id="r_tax_number">
		<div class="row-title">Tax/VAT Number</div>
		<div class="controls">
			<input type="text" class="input-text" name="tax_number" id="tax_number" value="<?php echo $store->getTaxNumber(); ?>">
		</div>
	</div>
	<!-- <div class="row" id="r_theme_background">
		<div class="row-title">Theme Background</div>
		<div class="controls">
			<input type="text" class="input-text" name="theme_background" id="theme_background" value="<?php echo $store->getThemeBackground(); ?>">
		</div>
	</div> -->
	<div class="row" id="r_theme_background">
		<div class="row-title">Theme Background</div>
		<div class="controls">
			<input type="text" class="input-text" name="theme_background" id="theme_background" value="<?php echo $store->getThemeBackground(); ?>">
		</div>
	</div>
	<script>
		require(['jquery', 'colorpicker'], function($) {
			$('#theme_background').ColorPicker({
				onSubmit: function(hsb, hex, rgb, el) {
					$(el).val(hex);
					$(el).ColorPickerHide();
				},
				onBeforeShow: function () {
					$(this).ColorPickerSetColor(this.value);
				},
				onChange: function(hsb, hex, rgb) {
					$('#theme_background').val(hex);
				}
			})
			.bind('keyup', function(){
				$(this).ColorPickerSetColor(this.value);
			});
		});
	</script>
	<div class="row" id="r_shop_title">
		<div class="row-title">Shop Name</div>
		<div class="controls">
			<input type="text" class="input-text" name="shop_title" id="shop_title" value="<?php echo $store->getShopTitle(); ?>">
		</div>
	</div>
	<div class="row" id="r_shop_logo">
		<div class="row-title">Shop Logo</div>
		<div class="controls">
			<input type="text" class="input-text" name="shop_logo" id="shop_logo" value="<?php echo $store->getShopLogo(); ?>">
		</div>
	</div>
	<div class="row" id="r_shop_cover">
		<div class="row-title">Shop Cover</div>
		<div class="controls">
			<input type="text" class="input-text" name="shop_cover" id="shop_cover" value="<?php echo $store->getShopCover(); ?>">
		</div>
	</div>
	<div class="row" id="r_shop_locality">
		<div class="row-title">Shop Locality</div>
		<div class="controls">
			<input type="text" class="input-text" name="shop_locality" id="shop_locality" value="<?php echo $store->getShopLocality(); ?>">
		</div>
	</div>
</form>